name: Format Code

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install js-beautify
        run: npm install js-beautify

      - name: Format EJS files
        run: npx js-beautify -r "**/*.ejs" --type html

      - name: Format HTML files
        run: npx js-beautify -r "**/*.html" --type html

      - name: Format CSS files
        run: npx js-beautify -r "**/*.css" --type css

      - name: Format JS files
        run: npx js-beautify -r "**/*.js" --type js

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "Auto-format code with js-beautify"
          title: "Auto-format code"
          body: |
            This PR automatically formats code using js-beautify.
            
            Files formatted:
            - EJS files
            - HTML files  
            - CSS files
            - JS files
          branch: format/auto-format-code
          delete-branch: true